MyDemoOrg/force-app/main/default/objects/Job_Posting__c/Job_Posting__c.object-meta.xml
<CustomObject>
    <label>Job Posting</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Job Post</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Postings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MyDemoOrg/force-app/main/default/objects/Job_Posting__c/fields/Sample_Text__c.field-meta.xml
<CustomField>
    <fullName>Sample_Text__c</fullName>
    <label>Sample Text</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

MyDemoOrg/force-app/main/default/classes/SampleTestClass.cls
@isTest(SeeAllData=true)
public class SampleTestClass {
    static testMethod void sampleOne(){
        Test.startTest() ;
        User u = [select id from User where id = '00528000000IsbM'];
        Job_Posting__c sam = [select id,Sample_Text__c from Job_Posting__c where id = 'a0K0I00000RYIL6UAP'];
        System.runAs(u){
            sam.Sample_Text__c = 'test';
            update sam;
        }
        Test.stopTest() ;
    } 
}