MyDemoOrg/force-app/main/default/objects/Account/fields/Account_textarea__c.field-meta.xml
<CustomField>
    <fullName>Account_textarea__c</fullName>
    <label>Account textarea</label>
    <type>TextArea</type>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/Multi_Language__c.field-meta.xml
<CustomField>
    <fullName>Multi_Language__c</fullName>
    <label>Multi Language</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Hindi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MyDemoOrg/force-app/main/default/classes/CodeTestingSampleClass.cls
public class CodeTestingSampleClass {
        
    public static void samplemethod(){
        List<InnerClass> lstofinner = new List<InnerClass>();
        for(Account acc: [SELECT id,name,Industry,Multi_Language__c,Account_textarea__c FROM Account limit 10]){
            InnerClass test = new InnerClass();
            test.firstmember = acc.name;
            test.secondmember = acc.Account_textarea__c;                        
            test.lstofString = (List<String>) acc.Multi_Language__c.split(';');
            lstofinner.add(test);
        }
        System.debug('lstofinner: '+lstofinner);
    }
    
    public class InnerClass{
        String firstmember;
        String secondmember;
        List<String> lstofString = new List<String>();
    }
}