MyDemoOrg/force-app/main/default/objects/Account/fields/Account_textarea__c.field-meta.xml
<CustomField>
    <fullName>Account_textarea__c</fullName>
    <label>Account textarea</label>
    <type>TextArea</type>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/fferpcore__IsBillingAddressValidated__c.field-meta.xml
<CustomField>
    <fullName>fferpcore__IsBillingAddressValidated__c</fullName>
    <description>Indicates whether the billing address has been validated against the addresses in the external tax calculation service.</description>
    <formula>fferpcore__MaterializedBillingAddressValidated__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates whether the billing address has been validated against the addresses in the external tax calculation service.</inlineHelpText>
    <label>Billing Address Validated</label>
    <type>Checkbox</type>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/fferpcore__IsShippingAddressValidated__c.field-meta.xml
<CustomField>
    <fullName>fferpcore__IsShippingAddressValidated__c</fullName>
    <description>Indicates whether the shipping address has been validated against the addresses in the external tax calculation service.</description>
    <formula>fferpcore__MaterializedShippingAddressValidated__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates whether the shipping address has been validated against the addresses in the external tax calculation service.</inlineHelpText>
    <label>Shipping Address Validated</label>
    <type>Checkbox</type>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/fferpcore__MaterializedBillingAddressValidated__c.field-meta.xml
<CustomField>
    <fullName>fferpcore__MaterializedBillingAddressValidated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used by Foundations to indicate that an address has been validated when Update Address Validated Fields is selected in the FDN Common Object Settings custom setting.</description>
    <label>Billing Address Validated Reference</label>
    <type>Checkbox</type>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/fferpcore__MaterializedShippingAddressValidated__c.field-meta.xml
<CustomField>
    <fullName>fferpcore__MaterializedShippingAddressValidated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used by Foundations to indicate that an address has been validated when Update Address Validated Fields is selected in the FDN Common Object Settings custom setting.</description>
    <label>Shipping Address Validated Reference</label>
    <type>Checkbox</type>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/fferpcore__OutputVatCode__c.field-meta.xml
<CustomField>
    <fullName>fferpcore__OutputVatCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The tax code to be used when calculating tax in a VAT or GST company.</description>
    <inlineHelpText>The tax code to be used when calculating tax in a VAT or GST company.</inlineHelpText>
    <label>Output VAT/GST Code</label>
    <referenceTo>fferpcore__TaxCode__c</referenceTo>
    <relationshipLabel>Accounts (Output VAT/GST Code)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/fferpcore__SalesTaxStatus__c.field-meta.xml
<CustomField>
    <fullName>fferpcore__SalesTaxStatus__c</fullName>
    <description>The tax status for this account for SUT companies.</description>
    <inlineHelpText>The tax status for this account for SUT companies.</inlineHelpText>
    <label>Sales Tax Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Taxable</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Exempt for Qualifying Products</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/fferpcore__TaxCode1__c.field-meta.xml
<CustomField>
    <fullName>fferpcore__TaxCode1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The first SUT tax code for this account.</description>
    <inlineHelpText>The first SUT tax code for this account.</inlineHelpText>
    <label>Tax Code 1</label>
    <referenceTo>fferpcore__TaxCode__c</referenceTo>
    <relationshipLabel>Accounts (Tax Code 1)</relationshipLabel>
    <relationshipName>AccountsTC1</relationshipName>
    <type>Lookup</type>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/fferpcore__TaxCode2__c.field-meta.xml
<CustomField>
    <fullName>fferpcore__TaxCode2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The second SUT tax code for this account.</description>
    <inlineHelpText>The second SUT tax code for this account.</inlineHelpText>
    <label>Tax Code 2</label>
    <referenceTo>fferpcore__TaxCode__c</referenceTo>
    <relationshipLabel>Accounts (Tax Code 2)</relationshipLabel>
    <relationshipName>AccountsTC2</relationshipName>
    <type>Lookup</type>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/fferpcore__TaxCode3__c.field-meta.xml
<CustomField>
    <fullName>fferpcore__TaxCode3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The third SUT tax code for this account.</description>
    <inlineHelpText>The third SUT tax code for this account.</inlineHelpText>
    <label>Tax Code 3</label>
    <referenceTo>fferpcore__TaxCode__c</referenceTo>
    <relationshipLabel>Accounts (Tax Code 3)</relationshipLabel>
    <relationshipName>AccountsTC3</relationshipName>
    <type>Lookup</type>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/fferpcore__TaxCountryCode__c.field-meta.xml
<CustomField>
    <fullName>fferpcore__TaxCountryCode__c</fullName>
    <description>Code for the European Union country in which this account operates. You can update the entries in this custom picklist if required.
The country code is required for the correct reporting of VAT on cross-border trades within the European Union.</description>
    <inlineHelpText>The country code for this account. This is required for correct reporting of VAT on cross-border trades within the European Union.</inlineHelpText>
    <label>Tax Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>fferpcore__TaxCountryCode</valueSetName>
    </valueSet>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/fferpcore__ValidatedBillingCity__c.field-meta.xml
<CustomField>
    <fullName>fferpcore__ValidatedBillingCity__c</fullName>
    <label>Validated Billing City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/fferpcore__ValidatedBillingCountry__c.field-meta.xml
<CustomField>
    <fullName>fferpcore__ValidatedBillingCountry__c</fullName>
    <label>Validated Billing Country</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/fferpcore__ValidatedBillingPostalCode__c.field-meta.xml
<CustomField>
    <fullName>fferpcore__ValidatedBillingPostalCode__c</fullName>
    <label>Validated Billing Zip/Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/fferpcore__ValidatedBillingState__c.field-meta.xml
<CustomField>
    <fullName>fferpcore__ValidatedBillingState__c</fullName>
    <label>Validated Billing State/Province</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/fferpcore__ValidatedBillingStreet__c.field-meta.xml
<CustomField>
    <fullName>fferpcore__ValidatedBillingStreet__c</fullName>
    <label>Validated Billing Street</label>
    <type>TextArea</type>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/fferpcore__ValidatedShippingCity__c.field-meta.xml
<CustomField>
    <fullName>fferpcore__ValidatedShippingCity__c</fullName>
    <label>Validated Shipping City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/fferpcore__ValidatedShippingCountry__c.field-meta.xml
<CustomField>
    <fullName>fferpcore__ValidatedShippingCountry__c</fullName>
    <label>Validated Shipping Country</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/fferpcore__ValidatedShippingPostalCode__c.field-meta.xml
<CustomField>
    <fullName>fferpcore__ValidatedShippingPostalCode__c</fullName>
    <label>Validated Shipping Zip/Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/fferpcore__ValidatedShippingState__c.field-meta.xml
<CustomField>
    <fullName>fferpcore__ValidatedShippingState__c</fullName>
    <label>Validated Shipping State/Province</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/fferpcore__ValidatedShippingStreet__c.field-meta.xml
<CustomField>
    <fullName>fferpcore__ValidatedShippingStreet__c</fullName>
    <label>Validated Shipping Street</label>
    <type>TextArea</type>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/fferpcore__VatRegistrationNumber__c.field-meta.xml
<CustomField>
    <fullName>fferpcore__VatRegistrationNumber__c</fullName>
    <description>Identifying number used for VAT purposes.</description>
    <inlineHelpText>Identifying number used for tax purposes.</inlineHelpText>
    <label>Tax Registration Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/fferpcore__VatStatus__c.field-meta.xml
<CustomField>
    <fullName>fferpcore__VatStatus__c</fullName>
    <description>The tax status for this account for VAT/GST accounts.</description>
    <inlineHelpText>The tax status for this account for VAT/GST accounts.</inlineHelpText>
    <label>Tax Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>EC Non-registered</fullName>
            </value>
            <value>
                <fullName>EC Registered</fullName>
            </value>
            <value>
                <fullName>Export</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/ImageURL__c.field-meta.xml
<CustomField>
    <fullName>ImageURL__c</fullName>
    <label>ImageURL</label>
    <type>Url</type>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/Potential_Value__c.field-meta.xml
<CustomField>
    <fullName>Potential_Value__c</fullName>
    <description>This field is created for learning purpose from trail head and it will sum the expected revenue from related opportunities.</description>
    <label>Potential Value</label>
    <summarizedField>Opportunity.ExpectedRevenue</summarizedField>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/Sample_City__c.field-meta.xml
<CustomField>
    <fullName>Sample_City__c</fullName>
    <label>Sample City</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/Sample_Long_Text_Area_Field__c.field-meta.xml
<CustomField>
    <fullName>Sample_Long_Text_Area_Field__c</fullName>
    <label>Sample Long Text Area Field</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/SinglePicklist__c.field-meta.xml
<CustomField>
    <fullName>SinglePicklist__c</fullName>
    <label>SinglePicklist</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FirstValue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/SLASerialNumber__c.field-meta.xml
<CustomField>
    <fullName>SLASerialNumber__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>SLA Serial Number</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/Test__c.field-meta.xml
<CustomField>
    <fullName>Test__c</fullName>
    <formula>TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Test</label>
    <type>Date</type>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/Test_Text_Field_Sam__c.field-meta.xml
<CustomField>
    <fullName>Test_Text_Field_Sam__c</fullName>
    <label>Province</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Value</fullName>
            </value>
            <value>
                <fullName>second vale</fullName>
            </value>
            <value>
                <fullName>jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Account/fields/Test_Unique_Field__c.field-meta.xml
<CustomField>
    <fullName>Test_Unique_Field__c</fullName>
    <label>Test Unique Field</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

MyDemoOrg/force-app/main/default/classes/CompassCanvasController.cls
public class CompassCanvasController {
	
    public String environment { get; set; }
    public String parameterJSON { get; set; }
    
    public CompassCanvasController(ApexPages.StandardController controller) {
		environment = getEnvironmentName();
        Account tempAcc;
        Map<Id,Account> mapAccount = new Map<Id, Account>(
            [SELECT AccountNumber,AccountSource,Account_textarea__c,Active__c,AnnualRevenue,BillingAddress,BillingCity,
                                      BillingCountry,BillingGeocodeAccuracy,BillingLatitude,BillingLongitude,BillingPostalCode,BillingState,BillingStreet,ChannelProgramLevelName,
                                      ChannelProgramName,CleanStatus,CreatedById,CreatedDate,CustomerPriority__c,DandbCompanyId,Description,DunsNumber,Fax,fferpcore__ExemptionCertificate__c,
                                      fferpcore__IsBillingAddressValidated__c,fferpcore__IsShippingAddressValidated__c,fferpcore__MaterializedBillingAddressValidated__c,fferpcore__MaterializedShippingAddressValidated__c,
                                      fferpcore__OutputVatCode__c,fferpcore__SalesTaxStatus__c,fferpcore__TaxCode1__c,fferpcore__TaxCode2__c,fferpcore__TaxCode3__c,fferpcore__TaxCountryCode__c,
                                      fferpcore__ValidatedBillingCity__c,fferpcore__ValidatedBillingCountry__c,fferpcore__ValidatedBillingPostalCode__c,fferpcore__ValidatedBillingState__c,fferpcore__ValidatedBillingStreet__c,
                                      fferpcore__ValidatedShippingCity__c,fferpcore__ValidatedShippingCountry__c,fferpcore__ValidatedShippingPostalCode__c,fferpcore__ValidatedShippingState__c,
                                      fferpcore__ValidatedShippingStreet__c,fferpcore__VatRegistrationNumber__c,fferpcore__VatStatus__c,Id,ImageURL__c,Industry,IsCustomerPortal,IsDeleted,IsPartner,Jigsaw,JigsawCompanyId,
                                      LastActivityDate,LastModifiedById,LastModifiedDate,LastReferencedDate,LastViewedDate,MasterRecordId,NaicsCode,NaicsDesc,Name,NumberOfEmployees,NumberofLocations__c,
                                      OwnerId,Ownership,ParentId,Phone,PhotoUrl,Potential_Value__c,Rating,Sample_City__c,Sample_Long_Text_Area_Field__c,ShippingAddress,ShippingCity,ShippingCountry,ShippingGeocodeAccuracy,
                                      ShippingLatitude,ShippingLongitude,ShippingPostalCode,ShippingState,ShippingStreet,Sic,SicDesc,SinglePicklist__c,Site,SLAExpirationDate__c,SLASerialNumber__c,SLA__c,SystemModstamp,
                                      Test_Text_Field_Sam__c,Test_Unique_Field__c,Test__c,TickerSymbol,Tradestyle,Type,UpsellOpportunity__c,Website,YearStarted FROM Account Limit 1]);
        
        for(Account acc  :mapAccount.values()){
            tempAcc = acc;
        }
        
    }
	
    private string getEnvironmentName() {
        organization org = [Select isSandbox from organization];
        if (!org.isSandbox == true) {
            return 'Prod';
        } else {
            return 'Sandbox';
        }    
    }
}