MyDemoOrg/force-app/main/default/objects/Contact/fields/Account_Info__c.field-meta.xml
<CustomField>
    <fullName>Account_Info__c</fullName>
    <label>Account Info</label>
    <type>TextArea</type>
</CustomField>

MyDemoOrg/force-app/main/default/objects/Contact/fields/Sample_Address__c.field-meta.xml
<CustomField>
    <fullName>Sample_Address__c</fullName>
    <label>Sample Address</label>
    <type>TextArea</type>
</CustomField>

MyDemoOrg/force-app/main/default/classes/AccountHelper.cls
public class AccountHelper {
    /*
    public static Boolean updateContactAddress(List<Contact> inputListContact){
        System.debug('AccountHelper inputListContact : '+inputListContact);
        List<Contact> updateContact = new List<Contact>();
        for(Contact con : inputListContact){
            con.Sample_Address__c = con.Account_Info__c;
            updateContact.add(con);
        }
        if(updateContact != null || !updateContact.isEmpty()){
            update inputListContact;
            return true;
        }else{
            return false;
        }
    }
    public static void temp(Account acclist){
        
         Contact test =  new  Contact (); 
        Contact a = [Select Id from Contact limit 1 ];
        system.debug(a);
        test.Sample_Address__c = a.name;
        insert test;
        system.debug('new account inserted with ID ' + test.id );
   
        
        
            
    }
    */

}